name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
    
  deploy:
    runs-on: ubuntu-latest
    needs: build # This job runs after 'build'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/
            cd /var/www/
            
            if [ -d "woody-app" ]; then
              cd /var/www/woody-app
              git pull origin main
            elsle
              git clone https://github.com/f-oni/woody-app.git
            fi

            cd /var/www/woody-app
            git pull origin main

            npm install
            pm2 restart index.js || pm2 start index.js
  